### ISSUE TITLE
script to join a number of regions together to make one single region

### ISSUE THREAD

**Issue by milenaveneziani** [MPAS-Dev/geometric_features#41] opened 2016-09-09 16:51 UTC
@xylar, @pwolfram, @douglasjacobsen: tugging you on this, as you are probably most interested to provide input here.

Yesterday, I was trying to create a mask file for ocean basins, and specifically for 2 groups: oceanBasins and oceanBasinsMOC. These groups contain the ocean basins that can now be reproduced by using the drivers that @xylar wrote a few months back. 
Let us take Atlantic_MOC as an example. 
The problem is that the corresponding geojson file for this region is a collection of the subregions that make up Atlantic_MOC, whereas what we really need is a single region, called Atlantic_MOC, that is the result of the joint subregional polygons.
This way, say for the oceanBasinsMOC group, we will have 2 single regions: Atlantic_MOC and IndoPacific_MOC.
Does this make sense?

Would it be hard to write such a script?

**Comment by xylar** [comment] 2016-09-09 17:37
@milenaveneziani, I get what you're saying.  Presumably rather than going through the trouble of joining the geometry into a single region, what is needed is a way to collect geometry from multiple regions together and give it a different name.  I can't recall if something to do that already exists but I think so. @douglasjacobsen, can you comment?

@milenaveneziani, can you be more specific about what the needs are?  How exactly are you using the geojson files so I understand whether it matters that the geometry itself gets fused together as opposed to just giving a single name to the collection of geometry.

**Comment by milenaveneziani** [comment] 2016-09-09 17:52
@xylar: I talked with Doug yesterday (he explained the whole process to me, which is why I came to the conclusion that we needed this issue open), and he doesn't think there is such a script now.
We need one single, fused region because we will need to compute specific quantities on each of them. For example MOC or meridional heat transport: we will want to compute these quantities over Atlantic_MOC and IndoPacific_MOC as whole regions, not as a collection of subregions. Same goes for the simple oceanBasins groups: we will want a maskfile for the fused Atlantic, SO, etc.

@douglasjacobsen thought that we shouldn't create these regions once and for all, but that it would be better to have a driver (similar to the one you have to merge the features) that would join the regions. There should of course be a provenance of how say Atlantic_MOC was created at a given time.

**Comment by xylar** [comment] 2016-09-09 17:59
@milenaveneziani, okay, I think I see.  I don't think you mean "fused" in the same way I mean "fused".  It doesn't sound like it matters whether the combined region is made up of multiple polygons or one single polygon, for example.

This should be quite easy to do.  I'll see if I can bang it out this evening.

**Comment by milenaveneziani** [comment] 2016-09-09 18:03
I am pretty sure it should be one polygon, especially as far as MOC and MHT computation goes (which are zonal integrals).

**Comment by milenaveneziani** [comment] 2016-09-09 18:04
And thanks. I didn't mean to suggest that you should take this on, especially with the ACME deadline looming on.

**Comment by xylar** [comment] 2016-09-09 19:07
@milenaveneziani, once the geojson geometry goes through the mask creator, you won't know whether the geojson file was one polygon or a bunch of them.  The mask file will look exactly the same and will have the same area.  But that's largely beside the point.  If I can produce a script that combines a bunch of features into a single feature (and lets you name it whatever you want), you won't really need to know the details of how that works as long as the ultimate result is one contiguous mask.

**Comment by milenaveneziani** [comment] 2016-09-09 19:49
I see what you mean, @xylar. That sounds perfectly fine to me. Thanks.

**Comment by xylar** [comment] 2016-09-09 20:57
@milenaveneziani, @douglasjacobsen , I've got a solution that mostly works.  As an example, here's the before and after on the Atlantic_MOC region:

Old method:
![atlantic_moc](https://cloud.githubusercontent.com/assets/4179064/18402576/60680d22-76e0-11e6-86b2-40aeed927078.png)

New method:
![atlantic_moc](https://cloud.githubusercontent.com/assets/4179064/18402598/78c4031c-76e0-11e6-9419-9d2d2700caba.png)

It mostly works but islands of any size aren't being preserved as holes.  For this particular use case, that's not going to be a problem because land gets cut out anyway but I can imagine other cases where this wouldn't be acceptable.  I'm going to see if I can figure out why this is happening before I submit a pull request.

Just wanted to give you a feel for what I'm doing.

**Comment by pwolfram** [comment] 2016-09-09 21:09
I don't know the exact algorithm used here @xylar, but if you need to preserve the holes you may be able to do this via a union using [shapely](http://toblerity.org/shapely/manual.html#set-theoretic-methods).  I've used shapely before and am of course happy to help out with this if you want.

**Comment by xylar** [comment] 2016-09-09 21:26
Turns out the problem is with our plotting software (which maybe I already knew) and not with the geojoson files, which look correct:
https://gist.github.com/xylar/5cda1cf32c80c0ab5259dda1a0ab1de5

**Comment by xylar** [comment] 2016-09-09 21:27
@pwolfram, I'm using shapely's cascade_union (which is much faster than union for multiple shapes).  The problem isn't with shapely, it's with our plotting routine in this repo.  Feel free to try to fix it...  I don't have time right now.

**Comment by xylar** [comment] 2016-09-09 22:06
#42 Should address this issue.

**Comment by xylar** [comment] 2016-09-19 20:43
This issue is addressed by #42.

**Closed by xylar** 2016-09-19 20:43 UTC
