### ISSUE TITLE
Plotting doesn't seem to work, at least not for Arctic basin

### ISSUE THREAD

**Issue by xylar** [MPAS-Dev/geometric_features#11] opened 2016-02-04 22:29 UTC
I just tried to plot all ocean basins and I found that the Arctic basin is plotting very differently in the 3 different views.  It looks correct on GitHub so I think the problem is somehow with the plotting and not with data itself.

![ocean_basins](https://cloud.githubusercontent.com/assets/4179064/12831857/dd5e93dc-cb96-11e5-9440-3e3acb6737e0.png)

In the figure, I think the North Pole plot is correct but the two mill plots are both very glitchy.  I'm not sure the Arctic basin is the only one that isn't plotting correctly but it seems to be the most extreme case.

**Comment by xylar** [comment] 2016-02-04 22:29
@douglasjacobsen or @pwolfram, this is a very low priority issue to fix, but maybe something to look into at some point.

**Comment by douglasjacobsen** [comment] 2016-02-04 22:48
On the plus side, github is able to plot it correctly...
https://github.com/MPAS-Dev/geometric_features/blob/master/ocean/region/Arctic_Ocean/region.geojson

**Comment by pwolfram** [comment] 2016-02-05 14:47
@xylar and @douglasjacobsen, I think the issue is the singularity at the pole and the way it is represented in the region.  I've added a few more projections at https://github.com/MPAS-Dev/geometric_features/pull/12: 'aeqd', 'eck4', 'cyl', 'merc', 'vandg' which you can try out by inserting these strings in the list at https://github.com/pwolfram/geometric_features/blob/additional_projection_types/plot_features.py#L109.

The reason github plots correctly is that it uses this projection (http://wiki.openstreetmap.org/wiki/EPSG:3857).  Unfortunately, basemap does not have this capability.  If we need to fix this we may have to leave the basemap api...

**Comment by xylar** [comment] 2016-02-05 22:56
@pwolfram, I guess I'm surprised that a simple cylindrical projection doesn't do the trick for the Arctic basin.  If I just plot the basins in matplotlib without using basemap, everything looks okay...

**Comment by pwolfram** [comment] 2016-02-06 22:55
This issue is fixed by #14 and I'm closing it.

**Closed by pwolfram** 2016-02-06 22:55 UTC
